sudo: required
services:
  - docker

before_install:
  - docker build -t nguyen8585/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nguyen8585/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react-stephen'
  env: 'Dockerreactstephen-env'
  bucket_name: 'elasticbeanstalk-us-east-2-908172795676'
  bucket_path: 'docker-react-stephen'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY





